name: Java CI

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.java'
      - '**/*.xml'
      - 'pom.xml'
      - 'src/**'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.java'
      - '**/*.xml'
      - 'pom.xml'
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17 and cache dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn -B clean verify

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/target/surefire-reports/*'

      - name: Upload code coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: '**/target/site/jacoco/*'

      - name: Archive build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: '**/target/*.jar'
